[project]
name = "axon_python"
version = "0.1.0"
description = "Python agent implementation for Axon"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "pydantic>=2.5.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
